// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU2KdH2gIGuXYGUCGVEE-nFOkX3FqH3lE',
    appId: '1:795338384836:web:9dd0e8b350530150fbb091',
    messagingSenderId: '795338384836',
    projectId: 'chatsapp-1ad35',
    authDomain: 'chatsapp-1ad35.firebaseapp.com',
    storageBucket: 'chatsapp-1ad35.firebasestorage.app',
    measurementId: 'G-R0Y8LGTYM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAii4mHoDAd7wORmihjRezl188ZSfX_lRc',
    appId: '1:795338384836:android:d476aa5027223b8cfbb091',
    messagingSenderId: '795338384836',
    projectId: 'chatsapp-1ad35',
    storageBucket: 'chatsapp-1ad35.firebasestorage.app',
  );

}